import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

const navigationConfig = [
    {
        key: 'home',
        path: '/home',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'parkings',
        path: '/parkings',
        title: 'Parkings',
        translateKey: 'nav.parkings',
        icon: 'parkings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'parkingMap',
        path: '/parking-map',
        title: 'Parking Map',
        translateKey: 'nav.parkingMap',
        icon: 'parkingMap',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'myReservations',
        path: '/my-reservations',
        title: 'My Reservations',
        translateKey: 'nav.myReservations',
        icon: 'reservations',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'messages',
        path: '/messages',
        title: 'Guard chats',
        translateKey: 'nav.messages',
        icon: 'messages',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'myPayments',
        path: '/my-payments',
        title: 'My Payments',
        translateKey: 'nav.myPayments',
        icon: 'payments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'myWallet',
        path: '/my-wallet',
        title: 'My Wallet',
        translateKey: 'nav.myWallet',
        icon: 'wallet',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'profile',
        path: '/profile',
        title: 'My Profile',
        translateKey: 'nav.profile',
        icon: 'profile',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'admin',
        path: '',
        title: 'Administration',
        translateKey: 'nav.admin.title',
        icon: 'admin',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'admin.dashboard',
                path: '/admin/dashboard',
                title: 'Admin Dashboard',
                translateKey: 'nav.admin.dashboard',
                icon: 'adminDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.users',
                path: '/admin/users',
                title: 'Users',
                translateKey: 'nav.admin.users',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.reservations',
                path: '/admin/reservations',
                title: 'All Reservations',
                translateKey: 'nav.admin.reservations',
                icon: 'adminReservations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.payments',
                path: '/admin/payments',
                title: 'All Payments',
                translateKey: 'nav.admin.payments',
                icon: 'adminPayments',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.parkings',
                path: '/admin/parkings',
                title: 'Manage Parkings',
                translateKey: 'nav.admin.parkings',
                icon: 'parkings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.parkingSlots',
                path: '/admin/parking-slots',
                title: 'Manage Slots',
                translateKey: 'nav.admin.parkingSlots',
                icon: 'parkings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.wallets',
                path: '/admin/wallets',
                title: 'Wallets',
                translateKey: 'nav.admin.wallets',
                icon: 'wallet',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.ownerDashboard',
                path: '/owner/dashboard',
                title: 'Owner Dashboard',
                translateKey: 'nav.admin.ownerDashboard',
                icon: 'ownerDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.guardDashboard',
                path: '/guard/dashboard',
                title: 'Guard Dashboard',
                translateKey: 'nav.admin.guardDashboard',
                icon: 'guardDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'owner',
        path: '',
        title: 'Parking Owner',
        translateKey: 'nav.owner.title',
        icon: 'ownerSection',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['parking_owner'],
        subMenu: [
            {
                key: 'owner.dashboard',
                path: '/owner/dashboard',
                title: 'Owner Dashboard',
                translateKey: 'nav.owner.dashboard',
                icon: 'ownerDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['parking_owner'],
                subMenu: [],
            },
            {
                key: 'owner.parkings',
                path: '/owner/parkings',
                title: 'My Parkings',
                translateKey: 'nav.owner.parkings',
                icon: 'parkings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['parking_owner'],
                subMenu: [],
            },
            {
                key: 'owner.reservations',
                path: '/owner/reservations',
                title: 'Reservations',
                translateKey: 'nav.owner.reservations',
                icon: 'reservations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['parking_owner'],
                subMenu: [],
            },
            {
                key: 'owner.earnings',
                path: '/owner/earnings',
                title: 'Earnings',
                translateKey: 'nav.owner.earnings',
                icon: 'ownerEarnings',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['parking_owner'],
                subMenu: [],
            },
            {
                key: 'owner.withdrawals',
                path: '/owner/withdrawals',
                title: 'Withdrawals',
                translateKey: 'nav.owner.withdrawals',
                icon: 'ownerWithdrawals',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['parking_owner'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'guard',
        path: '',
        title: 'Guard',
        translateKey: 'nav.guard.title',
        icon: 'guard',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['guard'],
        subMenu: [
            {
                key: 'guard.dashboard',
                path: '/guard/dashboard',
                title: 'Guard Dashboard',
                translateKey: 'nav.guard.dashboard',
                icon: 'guardDashboard',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['guard'],
                subMenu: [],
            },
            {
                key: 'guard.messages',
                path: '/messages',
                title: 'Guard chats',
                translateKey: 'nav.guard.messages',
                icon: 'messages',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['guard'],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
